//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_School_Diary.Data.EF_DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecture
    {
        public string Id { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public int Status { get; set; }
        public string StudentClassId { get; set; }
        public int Subject { get; set; }
        public string TeacherId { get; set; }
        public string Title { get; set; }
    
        public virtual StudentClass StudentClass { get; set; }
        public virtual User User { get; set; }
    }
}
